name: aca-docker-ci
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: docker build -t acrdemopatzdz.azurecr.io/fastapi:${{ github.sha }} ./azure/azure-aca-docker-ci/app

      - name: Push Docker image
        run: |
          az acr login --name acrdemopatzdz
          docker push acrdemopatzdz.azurecr.io/fastapi:${{ github.sha }}

      - name: Deploy to ACA
        run: |
          az containerapp update \
            --name aca-demo \
            --resource-group rg-aca-demo \
            --image acrdemopatzdz.azurecr.io/fastapi:${{ github.sha }}