name: deploy-azure-static
on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform apply
        working-directory: azure/azure-tf-staticweb-gha/infra
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="prefix=pat" \
            -var="rg_name=pat-static-rg" \
            -var="sa_name=patstaticdemo123"
      
      - name: Upload website
        run: |
          az storage blob upload-batch \
            -s ./azure/azure-tf-staticweb-gha/web -d '$web' --account-name patstaticdemo123